version: 0.1.0

name: Bespoke
description: Tailor newly created repositories for various use cases.
branding:
  color: red
  icon: menu

inputs:
  - name: customer_name
    description: Name of customer this repository is for.
    required: true

  - name: init_engagements
    description: Whether to initialize engagements.
    validvalues:
      - "yes"
      - "no"

  - name: debug
    description: Whether to display debug information during init.
    validvalues:
      - "no"
      - "yes"

init:
  uses: init.yml
